#!/bin/bash

# Copyright 2008-2018 Univa Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e -x

. /opt/tortuga/etc/tortuga.sh

TARBALL_NAME='VMwareTools-8.3.2-257589.tar.gz'
BASE_URL=`python -c "from tortuga.config.configManager import ConfigManager; print ConfigManager().getIntWebRootUrl(ConfigManager().getInstaller())"`

if [ -f /etc/vmware-tools/configured ]; then
    echo "VMware Tools already configured"
else
    mkdir -p /etc/vmware-tools

    # Get tarball
    wget -O /etc/vmware-tools/$TARBALL_NAME $BASE_URL/$TARBALL_NAME

    # Expand tarball
    /bin/tar -xzvf /etc/vmware-tools/$TARBALL_NAME -C /etc/vmware-tools

    # Configure tools
    /etc/vmware-tools/vmware-tools-distrib/vmware-install.pl -d
    touch /etc/vmware-tools/configured
fi
